Upgrade Swager Codegen-maven-plugin
Remved swagger annotations dependency as latest plugin generates
code using v3 annotations.

Small refactor to test classes and netwrok CM Proxy as it was causing
javax.validation.ConstraintDeclarationException: HV000151: A method
overriding another method must not redefine the parameter constraint
configuration test failures.

-Modified order of jsonData to be from 1st paramter to be
3rd parameter in DataRestController.createNode()

Issue-ID: CPS-205

Change-Id: Ie7911d7389dca587bde945d913f458de46027e0f
Signed-off-by: JosephKeenan <joseph.keenan@est.tech>