Create cm handle from NCMP Inventory returns Server Error caused by LogFormatUtils error
- An older version of Spring being pulled in as a transitive dependency of another library
  that was causing NoSuchMethodError:  org.springframework.core.log.LogFormatUtils.formatValue(...).
- Added bill of materials feature to solve just such issues. (Introduced into Spring 4).
- Removed the <version/> element from all possible spring libraries declared in our POM.
- Test is updated to cover AlreadyDefinedException. (http status 409)

Issue-ID: CPS-927
Signed-off-by: sourabh_sourabh <sourabh.sourabh@est.tech>
Change-Id: I48e21697f629b530e62d7bd6c1f2914115531928