Upgrade Swager Codegen-maven-plugin
Also Remved swagger annotations dependency as latest plugin generates
code using v3 annotations.

Small refactor to test classes and netwrok CM Proxy as it was causing
javax.validation.ConstraintDeclarationException: HV000151: A method
overriding another method must not redefine the parameter constraint
configuration test failures.

Issue-ID: CPS-205
Change-Id: Ie11f16aae5c562ef8c3765ed72d30926e3262ade
Signed-off-by: DylanB95EST <dylan.byrne@est.tech>